/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MakersRouteImport } from './routes/makers'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as MakersIndexRouteImport } from './routes/makers.index'
import { Route as MakersSlugRouteImport } from './routes/makers.$slug'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MakersRoute = MakersRouteImport.update({
  id: '/makers',
  path: '/makers',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const MakersIndexRoute = MakersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MakersRoute,
} as any)
const MakersSlugRoute = MakersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MakersRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/makers': typeof MakersRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/visit': typeof VisitRoute
  '/makers/$slug': typeof MakersSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/makers/': typeof MakersIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/visit': typeof VisitRoute
  '/makers/$slug': typeof MakersSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/makers': typeof MakersIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/makers': typeof MakersRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/visit': typeof VisitRoute
  '/makers/$slug': typeof MakersSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/makers/': typeof MakersIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/contact'
    | '/makers'
    | '/shop'
    | '/visit'
    | '/makers/$slug'
    | '/shop/$slug'
    | '/makers/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/contact'
    | '/visit'
    | '/makers/$slug'
    | '/shop/$slug'
    | '/makers'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/contact'
    | '/makers'
    | '/shop'
    | '/visit'
    | '/makers/$slug'
    | '/shop/$slug'
    | '/makers/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  MakersRoute: typeof MakersRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
  VisitRoute: typeof VisitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/makers': {
      id: '/makers'
      path: '/makers'
      fullPath: '/makers'
      preLoaderRoute: typeof MakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/makers/': {
      id: '/makers/'
      path: '/'
      fullPath: '/makers/'
      preLoaderRoute: typeof MakersIndexRouteImport
      parentRoute: typeof MakersRoute
    }
    '/makers/$slug': {
      id: '/makers/$slug'
      path: '/$slug'
      fullPath: '/makers/$slug'
      preLoaderRoute: typeof MakersSlugRouteImport
      parentRoute: typeof MakersRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface MakersRouteChildren {
  MakersSlugRoute: typeof MakersSlugRoute
  MakersIndexRoute: typeof MakersIndexRoute
}

const MakersRouteChildren: MakersRouteChildren = {
  MakersSlugRoute: MakersSlugRoute,
  MakersIndexRoute: MakersIndexRoute,
}

const MakersRouteWithChildren =
  MakersRoute._addFileChildren(MakersRouteChildren)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  MakersRoute: MakersRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
  VisitRoute: VisitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
